package Oracle.Vista;

import Oracle.Vista.Historial_Laboral.Historial_LaboralRead;
import Oracle.Vista.Historial_Laboral.Historial_LaboralUpdate;
import Oracle.Vista.Historial_Laboral.Historial_LaboralCreate;
import Oracle.Vista.Historial_Laboral.Historial_LaboralDelete;
import Oracle.Vista.Empleado.EmpleadoRead;
import Oracle.Vista.Empleado.EmpleadoUpdate;
import Oracle.Vista.Empleado.EmpleadoCreate;
import Oracle.Vista.Empleado.EmpleadoDelete;
import Oracle.Vista.Elementos_Asignados.Elementos_AsignadosDelete;
import Oracle.Vista.Elementos_Asignados.Elementos_AsignadosCreate;
import Oracle.Vista.Elementos_Asignados.Elementos_AsignadosRead;
import Oracle.Vista.Elementos_Asignados.Elementos_AsignadosUpdate;
import Oracle.Vista.Elemento.ElementoRead;
import Oracle.Vista.Elemento.ElementoUpdate;
import Oracle.Vista.Elemento.ElementoCreate;
import Oracle.Vista.Elemento.ElementoDelete;
import Oracle.Vista.Cargo.CargoCreate;
import Oracle.Vista.Cargo.CargoUpdate;
import Oracle.Vista.Cargo.CargoRead;
import Oracle.Vista.Cargo.CargoDelete;
import Oracle.Controlador.*;
import javax.swing.JDesktopPane;
/**
 * @Autor Samuel
 */
public class GUI extends javax.swing.JInternalFrame  {
    public static MasterEmpleado masterEmpleado = new MasterEmpleado();
    public static MasterElemento masterElemento = new MasterElemento();
    public static MasterCargo masterCargo = new MasterCargo();
    public static MasterHistorial_Laboral masterHistorial_Laboral = new MasterHistorial_Laboral();
    public static MasterElementos_Asignados masterElementos_Asignados = new MasterElementos_Asignados();
    public static MasterBitacora masterBitacora = new MasterBitacora();
    JDesktopPane desktopPane;
    
    public GUI() {
        initComponents();
    }
    
    public GUI(JDesktopPane desktopPane) {
        initComponents();
        this.desktopPane = desktopPane;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Empleados", "Elementos", "Cargos", "Historial_Laboral", "Elementos_Asignados" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Gestor");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Acción a realizar");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Tabla a manejar");

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Crear", "Leer", "Actualizar", "Borrar" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Ejecutar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Cerrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setText("Informes");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(31, 55, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(53, 53, 53)
                    .addComponent(jLabel3)
                    .addContainerGap(347, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(81, 81, 81)
                    .addComponent(jLabel3)
                    .addContainerGap(174, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if("Empleados".equals(jComboBox1.getSelectedItem().toString())){
            if("Leer".equals(jComboBox2.getSelectedItem().toString())){
                EmpleadoRead er = new EmpleadoRead(this.desktopPane);
                this.desktopPane.add(er);
                er.show();
            }else if("Borrar".equals(jComboBox2.getSelectedItem().toString())){
                EmpleadoDelete ed = new EmpleadoDelete(this.desktopPane);
                this.desktopPane.add(ed);
                ed.show();
            }else if("Actualizar".equals(jComboBox2.getSelectedItem().toString())){
                EmpleadoUpdate ed = new EmpleadoUpdate(this.desktopPane);
                this.desktopPane.add(ed);
                ed.show();
            }else if("Crear".equals(jComboBox2.getSelectedItem().toString())){
                EmpleadoCreate ed = new EmpleadoCreate(this.desktopPane);
                this.desktopPane.add(ed);
                ed.show();
            }
        }else if("Elementos".equals(jComboBox1.getSelectedItem().toString())){
            if("Leer".equals(jComboBox2.getSelectedItem().toString())){
                ElementoRead er = new ElementoRead(this.desktopPane);
                this.desktopPane.add(er);
                er.show();
            }else if("Borrar".equals(jComboBox2.getSelectedItem().toString())){
                ElementoDelete ed = new ElementoDelete(this.desktopPane);
                this.desktopPane.add(ed);
                ed.show();
            }else if("Actualizar".equals(jComboBox2.getSelectedItem().toString())){
                ElementoUpdate ed = new ElementoUpdate(this.desktopPane);
                this.desktopPane.add(ed);
                ed.show();
            }else if("Crear".equals(jComboBox2.getSelectedItem().toString())){
                ElementoCreate ed = new ElementoCreate(this.desktopPane);
                this.desktopPane.add(ed);
                ed.show();
            }
        }else if("Cargos".equals(jComboBox1.getSelectedItem().toString())){
            if("Leer".equals(jComboBox2.getSelectedItem().toString())){
                CargoRead cr = new CargoRead(this.desktopPane);
                this.desktopPane.add(cr);
                cr.show();
            }else if("Borrar".equals(jComboBox2.getSelectedItem().toString())){
                CargoDelete cd = new CargoDelete(this.desktopPane);
                this.desktopPane.add(cd);
                cd.show();
            }else if("Actualizar".equals(jComboBox2.getSelectedItem().toString())){
                CargoUpdate cd = new CargoUpdate(this.desktopPane);
                this.desktopPane.add(cd);
                cd.show();
            }else if("Crear".equals(jComboBox2.getSelectedItem().toString())){
                CargoCreate cd = new CargoCreate(this.desktopPane);
                this.desktopPane.add(cd);
                cd.show();
            }
        }else if("Historial_Laboral".equals(jComboBox1.getSelectedItem().toString())){
            if("Leer".equals(jComboBox2.getSelectedItem().toString())){
                Historial_LaboralRead cr = new Historial_LaboralRead(this.desktopPane);
                this.desktopPane.add(cr);
                cr.show();
            }else if("Borrar".equals(jComboBox2.getSelectedItem().toString())){
                Historial_LaboralDelete cd = new Historial_LaboralDelete(this.desktopPane);
                this.desktopPane.add(cd);
                cd.show();
            }else if("Actualizar".equals(jComboBox2.getSelectedItem().toString())){
                Historial_LaboralUpdate cd = new Historial_LaboralUpdate(this.desktopPane);
                this.desktopPane.add(cd);
                cd.show();
            }else if("Crear".equals(jComboBox2.getSelectedItem().toString())){
                Historial_LaboralCreate cd = new Historial_LaboralCreate(this.desktopPane);
                this.desktopPane.add(cd);
                cd.show();
            }
        }else if("Elementos_Asignados".equals(jComboBox1.getSelectedItem().toString())){
            if("Leer".equals(jComboBox2.getSelectedItem().toString())){
                Elementos_AsignadosRead cr = new Elementos_AsignadosRead(this.desktopPane);
                this.desktopPane.add(cr);
                cr.show();
            }else if("Borrar".equals(jComboBox2.getSelectedItem().toString())){
                Elementos_AsignadosDelete cd = new Elementos_AsignadosDelete(this.desktopPane);
                this.desktopPane.add(cd);
                cd.show();
            }else if("Actualizar".equals(jComboBox2.getSelectedItem().toString())){
                Elementos_AsignadosUpdate cd = new Elementos_AsignadosUpdate(this.desktopPane);
                this.desktopPane.add(cd);
                cd.show();
            }else if("Crear".equals(jComboBox2.getSelectedItem().toString())){
                Elementos_AsignadosCreate cd = new Elementos_AsignadosCreate(this.desktopPane);
                this.desktopPane.add(cd);
                cd.show();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Informes in = new Informes(this.desktopPane);
        this.desktopPane.add(in);
        in.show();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
