/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package Views;

import Cassandra.DTO.DTO_Persona;
import Controladores.MongoControlador;
import Controladores.CassandraControlador;
import Controladores.RedisControlador;
import Couch.model.Reports;
import Neo.controller.Controller;
import Neo.model.MovieDTO;
import Views.Cassandra.*;
import Views.MongoDB.vista_Listar;
import Views.REDIS.Actualizar_REDIS;

import Views.REDIS.Crear_REDIS;
import Views.REDIS.Eliminar_Redis;
import Views.REDIS.Listado;
import Views.REDIS.Listado2;
import Views.REDIS.Listado3;
import Views.REDIS.Listado4;
import Views.REDIS.Listado5;

import Oracle.Vista.*;
import Redis.Cliente.Terminal;
import Views.MongoDB.Views_InsertarMongo;
import Views.MongoDB.Views_eliminar;
import Views.Neo.ViewInsert;
import Views.Neo.ViewMovieCast;
import Views.Neo.ViewMovies;
import Views.Neo.ViewPersonMovie;
import Views.Neo.ViewPersons;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import view.couchdb.TEDTalkDelete;
import view.couchdb.TEDTalkInsert;
import view.couchdb.TEDTalkList;
import view.couchdb.TEDTalkUpdate;


/**
 *
 * @author Richard
 */
public class GUI_principal extends javax.swing.JFrame {

    /**
     * Creates new form descktop
     */
    public static Controladores.RedisControlador controlador_REDIS = new Controladores.RedisControlador();
MongoControlador conMongo=new MongoControlador();

    public GUI_principal() {
        initComponents();
        editMenu.disable();
        Menu_REDIS.disable();
        helpMenu2.disable();
        helpMenu3.disable();
        fileMenu.disable();
        jMenu1.disable();
        jMenu2.disable();
        Login l = new Login(this);
        this.desktopPane.add(l);
        l.show();
    }
    public void aceptar(){
        editMenu.enable();
        Menu_REDIS.enable();
        helpMenu2.enable();
        helpMenu3.enable();
        fileMenu.enable(); 
        jMenu1.enable();
        jMenu2.enable();
    }
    public JDesktopPane getdesktopPane(){
        return this.desktopPane;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        Menu_REDIS = new javax.swing.JMenu();
        crear_redis = new javax.swing.JMenuItem();
        actualizar_redis = new javax.swing.JMenuItem();
        eliminar_redis = new javax.swing.JMenuItem();
        visualizar_redis = new javax.swing.JMenuItem();
        listado2 = new javax.swing.JMenuItem();
        listado3 = new javax.swing.JMenuItem();
        listado4 = new javax.swing.JMenuItem();
        listado5 = new javax.swing.JMenuItem();
        listado_mongo = new javax.swing.JMenuItem();
        helpMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        contentMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        aboutMenuItem2 = new javax.swing.JMenuItem();
        helpMenu3 = new javax.swing.JMenu();
        contentMenuItem3 = new javax.swing.JMenuItem();
        aboutMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        fileMenu = new javax.swing.JMenu();
        VentanaMongo = new javax.swing.JMenuItem();
        VentanaMongo1 = new javax.swing.JMenuItem();
        VentanaMongo2 = new javax.swing.JMenuItem();
        VentanaMongo3 = new javax.swing.JMenuItem();
        VentanaMongo4 = new javax.swing.JMenuItem();
        VentanaMongo5 = new javax.swing.JMenuItem();
        VentanaMongo6 = new javax.swing.JMenuItem();
        VentanaMongo7 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        editMenu.setMnemonic('e');
        editMenu.setText("Oracle");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Activar");
        cutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(cutMenuItem);

        menuBar.add(editMenu);

        Menu_REDIS.setMnemonic('h');
        Menu_REDIS.setText("RedisDB");

        crear_redis.setText("Crear");
        crear_redis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crear_redisActionPerformed(evt);
            }
        });
        Menu_REDIS.add(crear_redis);

        actualizar_redis.setText("Actualizar");
        actualizar_redis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizar_redisActionPerformed(evt);
            }
        });
        Menu_REDIS.add(actualizar_redis);

        eliminar_redis.setText("Eliminar");
        eliminar_redis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar_redisActionPerformed(evt);
            }
        });
        Menu_REDIS.add(eliminar_redis);

        visualizar_redis.setText("Visualizar");
        visualizar_redis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizar_redisActionPerformed(evt);
            }
        });
        Menu_REDIS.add(visualizar_redis);

        listado2.setText("Listado2");
        listado2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listado2ActionPerformed(evt);
            }
        });
        Menu_REDIS.add(listado2);

        listado3.setText("Listado3");
        listado3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listado3ActionPerformed(evt);
            }
        });
        Menu_REDIS.add(listado3);

        listado4.setText("Listado4");
        listado4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listado4ActionPerformed(evt);
            }
        });
        Menu_REDIS.add(listado4);

        listado5.setText("Listado5");
        listado5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listado5ActionPerformed(evt);
            }
        });
        Menu_REDIS.add(listado5);

        listado_mongo.setText("Listado Mongo");
        listado_mongo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listado_mongoActionPerformed(evt);
            }
        });
        Menu_REDIS.add(listado_mongo);

        menuBar.add(Menu_REDIS);

        helpMenu2.setMnemonic('h');
        helpMenu2.setText("CassandraDB");

        jMenuItem2.setText("Create");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        helpMenu2.add(jMenuItem2);

        contentMenuItem2.setMnemonic('c');
        contentMenuItem2.setText("Read");
        contentMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentMenuItem2ActionPerformed(evt);
            }
        });
        helpMenu2.add(contentMenuItem2);

        jMenuItem3.setText("Update");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        helpMenu2.add(jMenuItem3);

        jMenuItem1.setText("Delete");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        helpMenu2.add(jMenuItem1);

        jMenuItem4.setText("Informe Total");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        helpMenu2.add(jMenuItem4);

        jMenuItem5.setText("Informe Datos Personales");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        helpMenu2.add(jMenuItem5);

        jMenuItem6.setText("Informe Academico");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        helpMenu2.add(jMenuItem6);

        jMenuItem7.setText("Informe Literario");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        helpMenu2.add(jMenuItem7);

        jMenuItem8.setText("Informe Academica No Suspendidos");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        helpMenu2.add(jMenuItem8);

        jMenuItem10.setText("Informe Hibrido Cassandra Redis");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        helpMenu2.add(jMenuItem10);

        jMenuItem9.setText("Respaldo");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        helpMenu2.add(jMenuItem9);

        aboutMenuItem2.setMnemonic('a');
        aboutMenuItem2.setText("About");
        aboutMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItem2ActionPerformed(evt);
            }
        });
        helpMenu2.add(aboutMenuItem2);

        menuBar.add(helpMenu2);

        helpMenu3.setMnemonic('h');
        helpMenu3.setText("Neo4j");

        contentMenuItem3.setMnemonic('c');
        contentMenuItem3.setText("PersonMovie");
        contentMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentMenuItem3ActionPerformed(evt);
            }
        });
        helpMenu3.add(contentMenuItem3);

        aboutMenuItem3.setMnemonic('a');
        aboutMenuItem3.setText("Insert Movie/Person");
        aboutMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItem3ActionPerformed(evt);
            }
        });
        helpMenu3.add(aboutMenuItem3);

        jMenuItem14.setText("MovieCast");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        helpMenu3.add(jMenuItem14);

        jMenuItem15.setText("Movies");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        helpMenu3.add(jMenuItem15);

        jMenuItem16.setText("Persons");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        helpMenu3.add(jMenuItem16);

        jMenuItem17.setText("Informe Mongo con Neo4J");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        helpMenu3.add(jMenuItem17);

        jMenuItem18.setText("Bakcup");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        helpMenu3.add(jMenuItem18);

        menuBar.add(helpMenu3);

        fileMenu.setMnemonic('f');
        fileMenu.setText("MongoDB");

        VentanaMongo.setMnemonic('o');
        VentanaMongo.setText("Listar");
        VentanaMongo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentanaMongoActionPerformed(evt);
            }
        });
        VentanaMongo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                VentanaMongoKeyPressed(evt);
            }
        });
        fileMenu.add(VentanaMongo);

        VentanaMongo1.setMnemonic('o');
        VentanaMongo1.setText("Insertar");
        VentanaMongo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentanaMongo1ActionPerformed(evt);
            }
        });
        VentanaMongo1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                VentanaMongo1KeyPressed(evt);
            }
        });
        fileMenu.add(VentanaMongo1);

        VentanaMongo2.setMnemonic('o');
        VentanaMongo2.setText("Eliminar");
        VentanaMongo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentanaMongo2ActionPerformed(evt);
            }
        });
        VentanaMongo2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                VentanaMongo2KeyPressed(evt);
            }
        });
        fileMenu.add(VentanaMongo2);

        VentanaMongo3.setMnemonic('o');
        VentanaMongo3.setText("ReporteTOTAL");
        VentanaMongo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentanaMongo3ActionPerformed(evt);
            }
        });
        VentanaMongo3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                VentanaMongo3KeyPressed(evt);
            }
        });
        fileMenu.add(VentanaMongo3);

        VentanaMongo4.setMnemonic('o');
        VentanaMongo4.setText("Reporte Simple");
        VentanaMongo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentanaMongo4ActionPerformed(evt);
            }
        });
        VentanaMongo4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                VentanaMongo4KeyPressed(evt);
            }
        });
        fileMenu.add(VentanaMongo4);

        VentanaMongo5.setMnemonic('o');
        VentanaMongo5.setText("Reporte solo Es");
        VentanaMongo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentanaMongo5ActionPerformed(evt);
            }
        });
        VentanaMongo5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                VentanaMongo5KeyPressed(evt);
            }
        });
        fileMenu.add(VentanaMongo5);

        VentanaMongo6.setMnemonic('o');
        VentanaMongo6.setText("Reporte vivienndas");
        VentanaMongo6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentanaMongo6ActionPerformed(evt);
            }
        });
        VentanaMongo6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                VentanaMongo6KeyPressed(evt);
            }
        });
        fileMenu.add(VentanaMongo6);

        VentanaMongo7.setMnemonic('o');
        VentanaMongo7.setText("Reportes Minimos");
        VentanaMongo7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentanaMongo7ActionPerformed(evt);
            }
        });
        VentanaMongo7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                VentanaMongo7KeyPressed(evt);
            }
        });
        fileMenu.add(VentanaMongo7);

        jMenuItem13.setText("Informe Mongo Cassandra");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        fileMenu.add(jMenuItem13);

        menuBar.add(fileMenu);

        jMenu2.setText("CouchDB");

        jMenuItem19.setText("List TedTalks");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem19);

        jMenuItem20.setText("Insert TedTalk");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem20);

        jMenuItem21.setText("Update TedTalk");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem21);

        jMenuItem22.setText("Detele TedTalk");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem22);

        jMenuItem23.setText("Report 1");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem23);

        jMenuItem24.setText("Report 2");
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem24);

        jMenuItem25.setText("Report 3");
        jMenuItem25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem25ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem25);

        jMenuItem26.setText("Report 4");
        jMenuItem26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem26ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem26);

        jMenuItem27.setText("Report 5");
        jMenuItem27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem27ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem27);

        jMenuItem28.setText("Report Couch-Oracle");
        jMenuItem28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem28ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem28);

        menuBar.add(jMenu2);

        jMenu1.setText("Usuarios");

        jMenuItem11.setText("CrearUsuario");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem11);

        jMenuItem12.setText("Cambiar Contraseña");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem12);

        menuBar.add(jMenu1);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1064, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VentanaMongoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VentanaMongoKeyPressed
        // TODO add your handling code here:
        System.out.println("SIUU");
    }//GEN-LAST:event_VentanaMongoKeyPressed

    private void VentanaMongoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VentanaMongoActionPerformed
        // TODO add your handling code here:
        //AQUI 
        vista_Listar vistaMongo = new vista_Listar(this.desktopPane);
        this.desktopPane.add(vistaMongo);
        vistaMongo.show(); //migrando x=new  migrando(this.desktopPane);
        //this.desktopPane.add(x);
        //      x.show();
    }//GEN-LAST:event_VentanaMongoActionPerformed

    private void contentMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentMenuItem2ActionPerformed
        Read_Cassandra RC = new Read_Cassandra(this.desktopPane);
        this.desktopPane.add(RC);
        RC.show();
    }//GEN-LAST:event_contentMenuItem2ActionPerformed

    private void aboutMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItem2ActionPerformed
        About RC = new About(this.desktopPane);
        this.desktopPane.add(RC);
        RC.show();
    }//GEN-LAST:event_aboutMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Delete_Cassandra DC = new Delete_Cassandra(this.desktopPane);
        this.desktopPane.add(DC);
        DC.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Create_Cassandra CC = new Create_Cassandra(this.desktopPane);
        this.desktopPane.add(CC);
        CC.show();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        Update_Cassandra UC = new Update_Cassandra(this.desktopPane);
        this.desktopPane.add(UC);
        UC.show();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        Informes_Cassandra IC = new Informes_Cassandra(this.desktopPane, 1);
        this.desktopPane.add(IC);
        IC.show();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void crear_redisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crear_redisActionPerformed
        Crear_REDIS crear_redis = new Crear_REDIS(this.desktopPane);
        this.desktopPane.add(crear_redis);
        crear_redis.show();
    }//GEN-LAST:event_crear_redisActionPerformed

    private void actualizar_redisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizar_redisActionPerformed
        Actualizar_REDIS actualizar_redis = new Actualizar_REDIS(this.desktopPane);
        this.desktopPane.add(actualizar_redis);
        actualizar_redis.show();
    }//GEN-LAST:event_actualizar_redisActionPerformed

    private void eliminar_redisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar_redisActionPerformed
        Eliminar_Redis eliminar_redis = new Eliminar_Redis(this.desktopPane);
        this.desktopPane.add(eliminar_redis);
        eliminar_redis.show();
    }//GEN-LAST:event_eliminar_redisActionPerformed

    private void visualizar_redisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizar_redisActionPerformed
        Listado listado_redis = new Listado(this.desktopPane);
        this.desktopPane.add(listado_redis);
        listado_redis.show();
    }//GEN-LAST:event_visualizar_redisActionPerformed

    private void listado2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listado2ActionPerformed
        Listado2 listado_redis = new Listado2(this.desktopPane);
        this.desktopPane.add(listado_redis);
        listado_redis.show();
    }//GEN-LAST:event_listado2ActionPerformed

    private void listado3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listado3ActionPerformed
        Listado3 listado_redis = new Listado3(this.desktopPane);
        this.desktopPane.add(listado_redis);
        listado_redis.show();
    }//GEN-LAST:event_listado3ActionPerformed

    private void listado4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listado4ActionPerformed
        Listado4 listado_redis = new Listado4(this.desktopPane);
        this.desktopPane.add(listado_redis);
        listado_redis.show();
    }//GEN-LAST:event_listado4ActionPerformed

    private void listado5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listado5ActionPerformed
        Listado5 listado_redis = new Listado5(this.desktopPane);
        this.desktopPane.add(listado_redis);
        listado_redis.show();
    }//GEN-LAST:event_listado5ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        Informes_Cassandra IC = new Informes_Cassandra(this.desktopPane, 4);
        this.desktopPane.add(IC);
        IC.show();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        Informes_Cassandra IC = new Informes_Cassandra(this.desktopPane, 5);
        this.desktopPane.add(IC);
        IC.show();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        Informes_Cassandra IC = new Informes_Cassandra(this.desktopPane, 2);
        this.desktopPane.add(IC);
        IC.show();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        Informes_Cassandra IC = new Informes_Cassandra(this.desktopPane, 3);
        this.desktopPane.add(IC);
        IC.show();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        CassandraControlador MC = new CassandraControlador();
        MC.Respaldo();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void cutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutMenuItemActionPerformed
        GUI g = new GUI(this.desktopPane);
        this.desktopPane.add(g);
        g.show();
    }//GEN-LAST:event_cutMenuItemActionPerformed

    private void VentanaMongo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VentanaMongo1ActionPerformed
        // TODO add your handling code here:
        Views_InsertarMongo vista = new Views_InsertarMongo(this.desktopPane);
        this.desktopPane.add(vista);
        vista.show();
    }//GEN-LAST:event_VentanaMongo1ActionPerformed

    private void VentanaMongo1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VentanaMongo1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_VentanaMongo1KeyPressed

    private void VentanaMongo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VentanaMongo2ActionPerformed
        // TODO add your handling code here:sssssssssssss
        Views_eliminar vista = new Views_eliminar(this.desktopPane);
        this.desktopPane.add(vista);
        vista.show();
    }//GEN-LAST:event_VentanaMongo2ActionPerformed

    private void VentanaMongo2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VentanaMongo2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_VentanaMongo2KeyPressed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        Informes_Cassandra IC = new Informes_Cassandra(this.desktopPane, 6);
        this.desktopPane.add(IC);
        IC.show();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        CrearUsuario CU = new CrearUsuario(this.desktopPane);
        this.desktopPane.add(CU);
        CU.show();
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        CambiarPassword CP = new CambiarPassword(this.desktopPane);
        this.desktopPane.add(CP);
        CP.show();
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void VentanaMongo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VentanaMongo3ActionPerformed
        // TODO add your handling code here:
this.conMongo.Generar_pdf(1);
    }//GEN-LAST:event_VentanaMongo3ActionPerformed

    private void VentanaMongo3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VentanaMongo3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_VentanaMongo3KeyPressed

    private void VentanaMongo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VentanaMongo4ActionPerformed
this.conMongo.Generar_pdf(2);        // TODO add your handling code here:
    }//GEN-LAST:event_VentanaMongo4ActionPerformed

    private void VentanaMongo4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VentanaMongo4KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_VentanaMongo4KeyPressed

    private void VentanaMongo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VentanaMongo5ActionPerformed
this.conMongo.Generar_pdf(3);        // TODO add your handling code here:
    }//GEN-LAST:event_VentanaMongo5ActionPerformed

    private void VentanaMongo5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VentanaMongo5KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_VentanaMongo5KeyPressed

    private void VentanaMongo6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VentanaMongo6ActionPerformed
this.conMongo.Generar_pdf(4);        // TODO add your handling code here:
    }//GEN-LAST:event_VentanaMongo6ActionPerformed

    private void VentanaMongo6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VentanaMongo6KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_VentanaMongo6KeyPressed

    private void VentanaMongo7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VentanaMongo7ActionPerformed
this.conMongo.Generar_pdf(5);        // TODO add your handling code here:
    }//GEN-LAST:event_VentanaMongo7ActionPerformed

    private void VentanaMongo7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VentanaMongo7KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_VentanaMongo7KeyPressed

    private void listado_mongoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listado_mongoActionPerformed
        RedisControlador controlador = new RedisControlador();
        MongoControlador mcon = new MongoControlador();    
        
        
        try {
            Document documento = new Document();
            String nombre = "Informe_Hibrido_Redis_Mongo.pdf";
            
            
            PdfWriter.getInstance(documento, new FileOutputStream("./Informes/" + nombre));
            documento.open();
            
            PdfPTable tabla = new PdfPTable(4);
            
            ArrayList<String[]> listado = mcon.informes();
            for(String[] c:listado ){
                tabla.addCell(c[0]);
                tabla.addCell(c[1]);
                tabla.addCell(c[2]);
                tabla.addCell(c[3]);
            }
            
            
            documento.add(tabla);
            
            PdfPTable tabla2 = new PdfPTable(3);
            
            
            RedisControlador RC = new RedisControlador();
            RC.conectarREDIS();
            
            String[][] datosredis = RC.listarEmpleadosREDIS();
            
            for(int i=0;i<datosredis.length; i++){
                for(int j=0;j<datosredis[0].length; j++){
                    tabla2.addCell(datosredis[i][j]);
                }
            }
            
            documento.add(tabla2);
            RC.desconectarREDIS();
            
            documento.close();
            
            /*
            
            String [][] reporte=null;
            
            controlador.conectarREDIS();
            
            ArrayList<String[]> repo = null;
            
            reporte = controlador.listarEmpleadosREDIS();
            for(int i=0; i<reporte.length; i++){
            repo.add(reporte[i]);
            }
            System.out.println("\n Fin REDIS \n");
            ArrayList<String[]> listado = mcon.listar();
            for(String[] c:listado ){
            repo.add(c);
            }
            
            /*
            //controlador.generar_pdf(reporte, "/Desktop/Reporte_REDIS.pdf");
            //reporte = controlador.listarEmpleadoREDIS("500");
            //reporte = controlador.listarCargosREDIS();
            //reporte = controlador.listarEmpleadoAnoREDIS("2020");
            //reporte = controlador.listarEmpleadoSalarioREDIS(15000);
            /*controlador.insertarEmpleadosREDIS("500", "Alejandro Torres", "The ¡Boss!",
            "The ¡Boss!", "The ¡Boss!", 8, "Septiembre", "2001",
            "C:/Users/alejo/Desktop/perfil3.png");
            */
            //controlador.eliminarEmpleadosREDIS("emp500");
            controlador.backupREDIS();
            controlador.desconectarREDIS();
            
            
            //String binario = controlador.ImagenBinarioREDIS();
            //controlador.BinarioImagenREDIS(binario);
        } catch (FileNotFoundException ex) {
            java.util.logging.Logger.getLogger(Terminal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(GUI_principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_listado_mongoActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
            Document documento = new Document();
            String nombre = "Informe_Hibrido_Mongo_Cassandra.pdf";

            try {
                PdfWriter.getInstance(documento, new FileOutputStream("./Informes/" + nombre));
                documento.open();

                PdfPTable tabla = new PdfPTable(3);


                CassandraControlador MC = new CassandraControlador();

                tabla.addCell("Id");
                tabla.addCell("Carrera");
                tabla.addCell("Promedio");

                for (DTO_Persona dto: MC.ReadPersonas() ) {
                    tabla.addCell(dto.toStringI3().split(", ")[0]);
                    tabla.addCell(dto.toStringI3().split(", ")[1]);
                    tabla.addCell(dto.toStringI3().split(", ")[2]);
                }

                documento.add(tabla);
                
                PdfPTable tabla2 = new PdfPTable(6);


            MongoControlador mcon = new MongoControlador();
            ArrayList<String[]> listado = mcon.informes();
            for(String[] c:listado ){
                tabla2.addCell(c[0]);
                tabla2.addCell(c[1]);
                tabla2.addCell(c[2]);
                tabla2.addCell(c[3]);
                tabla2.addCell(c[4]);
                tabla2.addCell(c[5]);
            }
            
            
            documento.add(tabla2);
                
                documento.close();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Informes_Cassandra.class.getName()).log(Level.SEVERE, null, ex);
            } catch (DocumentException ex) {
                Logger.getLogger(Informes_Cassandra.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
        ViewMovieCast IC = new ViewMovieCast(this.desktopPane);
        this.desktopPane.add(IC);
        IC.show();
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void contentMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentMenuItem3ActionPerformed
        // TODO add your handling code here:
        ViewPersonMovie IC = new ViewPersonMovie(this.desktopPane);
        this.desktopPane.add(IC);
        IC.show();
    }//GEN-LAST:event_contentMenuItem3ActionPerformed

    private void aboutMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItem3ActionPerformed
        // TODO add your handling code here:
        ViewInsert IC = new ViewInsert(this.desktopPane);
        this.desktopPane.add(IC);
        IC.show();
    }//GEN-LAST:event_aboutMenuItem3ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
        ViewMovies IC = new ViewMovies(this.desktopPane);
        this.desktopPane.add(IC);
        IC.show();
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        // TODO add your handling code here:
        ViewPersons IC = new ViewPersons(this.desktopPane);
        this.desktopPane.add(IC);
        IC.show();
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        // TODO add your handling code here:
        Document documento = new Document();
        String nombre = "Informe_Hibrido_Mongo_Neo4J.pdf";

        try {
            PdfWriter.getInstance(documento, new FileOutputStream("./Informes/" + nombre));
            documento.open();

            //MongoDB
            PdfPTable tabla2 = new PdfPTable(6);

            MongoControlador mcon = new MongoControlador();
            ArrayList<String[]> listado = mcon.informes();
            for(String[] c:listado ){
                tabla2.addCell(c[0]);
                tabla2.addCell(c[1]);
                tabla2.addCell(c[2]);
                tabla2.addCell(c[3]);
                tabla2.addCell(c[4]);
                tabla2.addCell(c[5]);
            }
            
            documento.add(tabla2);
            
            // NEO4J
            
            Controller con_neo = new Controller();
            var movies = con_neo.getMovies();
            
            PdfPTable tabla = new PdfPTable(3);

            tabla.addCell("Title");
            tabla.addCell("Released");
            tabla.addCell("Tagline");

            for (MovieDTO m: movies) {
                tabla.addCell(m.getTitle()+"");
                tabla.addCell(m.getReleased()+"");
                tabla.addCell(m.getTagline()+"");
            }

            documento.add(tabla);

            documento.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Informes_Cassandra.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(Informes_Cassandra.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        // TODO add your handling code here:
        Controller MC = new Controller();
        MC.BackupMovies();
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        // TODO add your handling code here:
        TEDTalkList view = new TEDTalkList(this.desktopPane);
        this.desktopPane.add(view);
        view.show();
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        // TODO add your handling code here:
        TEDTalkInsert view = new TEDTalkInsert(this.desktopPane);
        this.desktopPane.add(view);
        view.show();
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        // TODO add your handling code here:
        TEDTalkUpdate view = new TEDTalkUpdate(this.desktopPane);
        this.desktopPane.add(view);
        view.show();
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
        // TODO add your handling code here:
        TEDTalkDelete view = new TEDTalkDelete(this.desktopPane);
        this.desktopPane.add(view);
        view.show();
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
        // TODO add your handling code here:
        Reports report = new Reports();
        report.report1();
    }//GEN-LAST:event_jMenuItem23ActionPerformed

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem24ActionPerformed
        // TODO add your handling code here:
        Reports report = new Reports();
        report.report2();
    }//GEN-LAST:event_jMenuItem24ActionPerformed

    private void jMenuItem25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem25ActionPerformed
        // TODO add your handling code here:
        Reports report = new Reports();
        report.report3();
    }//GEN-LAST:event_jMenuItem25ActionPerformed

    private void jMenuItem26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem26ActionPerformed
        // TODO add your handling code here:
        Reports report = new Reports();
        report.report4();
    }//GEN-LAST:event_jMenuItem26ActionPerformed

    private void jMenuItem27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem27ActionPerformed
        // TODO add your handling code here:
        Reports report = new Reports();
        report.report5();
    }//GEN-LAST:event_jMenuItem27ActionPerformed

    private void jMenuItem28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem28ActionPerformed
        // TODO add your handling code here:
        Reports report = new Reports();
        report.reportOracle();
    }//GEN-LAST:event_jMenuItem28ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Menu_REDIS;
    private javax.swing.JMenuItem VentanaMongo;
    private javax.swing.JMenuItem VentanaMongo1;
    private javax.swing.JMenuItem VentanaMongo2;
    private javax.swing.JMenuItem VentanaMongo3;
    private javax.swing.JMenuItem VentanaMongo4;
    private javax.swing.JMenuItem VentanaMongo5;
    private javax.swing.JMenuItem VentanaMongo6;
    private javax.swing.JMenuItem VentanaMongo7;
    private javax.swing.JMenuItem aboutMenuItem2;
    private javax.swing.JMenuItem aboutMenuItem3;
    private javax.swing.JMenuItem actualizar_redis;
    private javax.swing.JMenuItem contentMenuItem2;
    private javax.swing.JMenuItem contentMenuItem3;
    private javax.swing.JMenuItem crear_redis;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem eliminar_redis;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu2;
    private javax.swing.JMenu helpMenu3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem listado2;
    private javax.swing.JMenuItem listado3;
    private javax.swing.JMenuItem listado4;
    private javax.swing.JMenuItem listado5;
    private javax.swing.JMenuItem listado_mongo;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem visualizar_redis;
    // End of variables declaration//GEN-END:variables

}
